server:
  port: 0

spring:
  application:
    name: record
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/record
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

clients:
  nutritionIntake:
    name: nutritionIntake
    domainUrl: http://nutritionIntake
    retrieve-data:
      url: /api/nutritionIntake/{recordId}