# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: discovery-server-CICD-pipeline

on:
  workflow_dispatch:
    inputs:
      runWorkflow:
        description: 'Run the workflow'
        required: true
  push:
    paths:
      - 'microServices/discovery-server/**' 

jobs:
  discovery-service-cicd:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        cache: 'maven'
        distribution: corretto

    - name : Test && Build && Deploy
      working-directory: ./microServices/discovery-server
      run: |
        mvn test
        mvn install
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/discovery-server-tracker-app .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/discovery-server-tracker-app
